name: 'Deploy'

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_pub:    
    runs-on: self-hosted
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
    
    steps:
      - name: Execute remote
        uses: p1-gp/p1-tool-workflow@master
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER }}
          access_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repository: ${{ github.event.repository.name }}
          branch: ${GITHUB_REF:11}